### ISSUE TITLE
Run on Teensy 3.1/3.2

### ISSUE THREAD

**Issue by zensutherland** [levosos/Midier#10]
Love the idea for this, but i could not get it to compile on my Teensy 3.1 - This may very well be due to my ignorance, so please forgive me if this is a 'user issue' and nothing to do with the software.

The compile was attempted on the provided examples (Scales, Notes, etc) with the library. Below is the error message.

_In file included from /Users/zensutherland/Documents/Arduino/libraries/Midier/src/Midier.h:12:0,
                 from /Users/zensutherland/Documents/Arduino/Midi/midier/midier.ino:14:
/Users/zensutherland/Documents/Arduino/libraries/Midier/src/sequencer/sequencer.h:20:17: error: enumerator value -1 is outside the range of underlying type 'char'
         None = -1,_

**Comment by rotenbergrr** [comment]
Hi @zensutherland and thanks for reaching out!

I don't have any experience with Teensy boards. Can you please explain a bit how you compile the project?
Do you control the compilation command line that is executed?
If so, is the flag `-pedantic` passed to the compiler?

Did you install Midier using a library manager just like the one for Arduino, or did you clone this repository manually?

Thanks!

**Comment by MatrixRat** [comment]
Same as zensutherland, would like to get this library working on Teensy 3.0 and later.

Using Win10, Arduino IDE 1.8.15 and Teensyduino 1.54, arpeggino compiles for AVR boards eg, UNO, Leonardo, Mega, Teensy 2.0 and Teensy++ 2.0 but not for Teensy 3.0 or later.

Results were the same for installing Midier using library manager or manual install.
Compiler errors are same as zensutherland's post

Have just completed step one of the tutorial using an Arduino Leonardo and am seeing note messages being output from TX1 however would  like to get it working on a Teensy 3.0 or better and think it would be great to use this lib with Teensyduino's native Fortyseven Effects Midi library.

**Comment by CarloCattano** [comment]
Greetings ! I came across this issue . This is an incredible library and wanted to give it a spin on my Teensy 3.6 . Its quite simple with its own [usbMIDI() implementations](https://www.pjrc.com/teensy/td_midi.html) .  
I have forked the repo with that tiny initial change . I will test the most I can out of the library and report back . 
Thanks a lot for making this effort on Midier !

the fork that works out of the box on teensy (tested 3.6) for now , till an option is added to the official repo .
-https://github.com/CarloCattano/Midier

Its just a tiny change in src/midi.cpp  , comenting this lines and adding the usbMIDI way of writing it 
https://github.com/levosos/Midier/blob/a1f8ee5ad51951a1b7365e609f5bf7e5b1f902b2/src/midi/midi.cpp#L20-L22

should be like this instead for usb midi via teensy. 
https://github.com/CarloCattano/Midier/blob/82c4ccd24e35e01847efa06db8efd50a74bc84a5/src/midi/midi.cpp#L19-L23

You can edit it yourself find in  the files that complain in the arduino console when the errors popup , you should be able to see where Midier/src/Midi.cpp is installed

**Comment by CarloCattano** [comment]
Another thing that is just a quick hack is the addition of " signed char "  . Teensy assumes char to be unsigned .
Compiler complains about the conversion from unsigned int to int . 
-https://github.com/CarloCattano/Midier/commit/ad4f9020540ec129f264dd74fd1faed30903e0ef

**Comment by MatrixRat** [comment]
Thank you CarloCattano, will change hardware to suit T3.6, play with those links and report back.

**Comment by CarloCattano** [comment]
@MatrixRat I dont think you need to change hardware. T 3.1/3.2/3.6 should behave equally, if I'm not forgetting something obvious

**Comment by MatrixRat** [comment]
@CarloCattano Just to elaborate, soldered buttons etc to a Mega protoboard and need to be mindful of T3.6 V+  for Din Midi I/O. Have a T3.6 on a Talldog DUE breakout and plan to build so will work on a Mega as well thinking that with the extra I/O pins will not need to use 4067s earmarked for another project.
Am adding the Din Midi I/O as would like to be able to plug in say a Novation SL-25. Am not a real programmer and this library has got me interested and looks like excellent material to dig into C++ and learn some new tricks like there are code hieroglyphics here that I need to be able to understand and use in another Midi project, ~6K lines of working code..

**Comment by natehouk** [comment]
The issue is that Teensy is using C++11 and has different variable types defined. I made a pull request that fixes all issues for Teensy 4.1

**Comment by natehouk** [comment]
Here is the PR with the changes required for Teensy 4.1: https://github.com/razrotenberg/Midier/pull/14

**Comment by poetaster** [comment]
I get very similar problems compiling with the arduino rp2040 (pi pico) as target.  I'm using the older 1.8.x version of the ide and the 3.8.1 version of the pico sdk for arduino.  I also use this library very happily with the lgt8fx (https://github.com/poetaster/spires) ... so it seems to be a language feature thing.

Beside the unsigned char problem in note and sequencer (the enums with negative numbers) there seems to be a more general issue:

```
/home/mwa/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/bin/arm-none-eabi-g++ -I /tmp/arduino_build_383748/core -c -Werror=return-type -Wno-psabi -DCFG_TUSB_MCU=OPT_MCU_RP2040 -DUSBD_PID=0x000a -DUSBD_VID=0x2e8a -DUSBD_MAX_POWER_MA=250 "-DUSB_MANUFACTURER=\"Raspberry Pi\"" "-DUSB_PRODUCT=\"Pico\"" -DPICO_CYW43_ARCH_THREADSAFE_BACKGROUND=1 -DCYW43_LWIP=1 -DLWIP_IPV6=0 -DLWIP_IPV4=1 -DLWIP_IGMP=1 -DLWIP_CHECKSUM_CTRL_PER_NETIF=1 "-DARDUINO_VARIANT=\"rpipico\"" -DTARGET_RP2040 -DPICO_FLASH_SIZE_BYTES=2097152 -march=armv6-m -mcpu=cortex-m0plus -mthumb -ffunction-sections -fdata-sections -fno-exceptions -DARM_MATH_CM0_FAMILY -DARM_MATH_CM0_PLUS -MMD -iprefix/home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/ @/home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/lib/platform_inc.txt -I/home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/include -fno-rtti -std=gnu++17 -g -pipe -DF_CPU=200000000L -DARDUINO=10810 -DARDUINO_RASPBERRY_PI_PICO "-DBOARD_NAME=\"RASPBERRY_PI_PICO\"" -DARDUINO_ARCH_RP2040 -Os -DWIFICC=CYW43_COUNTRY_WORLDWIDE -I/home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/cores/rp2040 -I/home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/variants/rpipico -I/home/mwa/Arduino/libraries/Midier/src /tmp/arduino_build_383748/sketch/Notes.ino.cpp -o /tmp/arduino_build_383748/sketch/Notes.ino.cpp.o
In file included from /home/mwa/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/arm-none-eabi/include/c++/12.3.0/bits/specfun.h:45,
                 from /home/mwa/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/arm-none-eabi/include/c++/12.3.0/cmath:1935,
                 from /home/mwa/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/arm-none-eabi/include/c++/12.3.0/math.h:36,
                 from /home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/cores/rp2040/api/../../../ArduinoCore-API/api/ArduinoAPI.h:47,
                 from /home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/cores/rp2040/api/ArduinoAPI.h:2,
                 from /home/mwa/.arduino15/packages/rp2040/hardware/rp2040/3.8.1/cores/rp2040/Arduino.h:28,
                 from /tmp/arduino_build_383748/sketch/Notes.ino.cpp:1:
/home/mwa/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/arm-none-eabi/include/c++/12.3.0/bits/stl_algobase.h:319:26: error: '__gnu_debug' in namespace '::' does not name a type
  319 |     __niter_base(const ::__gnu_debug::_Safe_iterator<_Ite, _Seq,
```

Works fine on other targets like the lgt or a nano.

**Comment by poetaster** [comment]
To see if it's just a bitchy compiler thing I compressed the classes I needed into the namespace in a single file in this sketch:
https://github.com/poetaster/arduinoMI/tree/main/BraidsEnginesScarp

That works. Since I didn't need the sequencer stuff and am just using this to create scales/modes on the fly, it's sufficient. Not pretty.

That Braids sketch is using a port of Mutable instruments braids to arduino. The library I built is also a kludge. To get the compiler to find everything I had to declare #includes for all the c++ files and not just the headers. It feels all wrong. But it sounds really good :)
